# Generated by Django 5.0.7 on 2024-10-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_department_alter_classstudent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
