# Generated by Django 5.0.7 on 2024-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='absences',
            field=models.IntegerField(default=0),
        ),
    ]
